booking_rest/urls.py
from django.contrib import admin
from django.urls import path, include
from feedback.views import *
from booking.views import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('rooms', RoomViewSet)
router.register('feedback', MailView)


urlpatterns = [
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('', include(router.urls)),
    path('bookings/', BookingDetailsView.as_view({'get': 'get', 'post': 'post'}), name='bookroom',),          # Передает параметр 'id' комнаты в вьюшку
    path('front/', ObjectLimitPaginationView.as_view(), name='front'),
]

feedback/urls.py
from django.conf.urls.static import static
from django.urls import path
from .views import *

urlpatterns = [
    path('/feedback', MailView.as_view()),
    # path('img', ImageUploadView.as_view(), name='ImageUpload'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField


class BookStatus(models.Model):
    name = models.CharField(max_length=64, verbose_name='Статус брони')

    class Meta:
        verbose_name = 'Статус комнаты'
        verbose_name_plural = 'Статусы комнаты'

    def __str__(self):
        return self.name


class BookPayStatus(models.Model):
    name = models.CharField(max_length=64, verbose_name='Статус оплаты')

    class Meta:
        verbose_name = 'Статус оплаты'
        verbose_name_plural = 'Статусы оплаты'

    def __str__(self):
        return self.name


class CategoryRoom(models.Model):
    name = models.CharField(max_length=64, verbose_name='Название категории')

    class Meta:
        verbose_name = 'Категория комнаты'
        verbose_name_plural = 'Категории комнат'

    def __str__(self):
        return self.name


class VolumeRoom(models.Model):
    volume_name = models.CharField(max_length=64, verbose_name='Вместительность комнаты')

    class Meta:
        verbose_name = 'Вместительность комнаты'
        verbose_name_plural = 'Вместительность комнат'

    def __str__(self):
        return self.volume_name


class Room(models.Model):
    name = models.CharField(max_length=64, verbose_name='Название комнаты')
    price = models.IntegerField(default=0, blank=False, verbose_name='Цена')
    category = models.ForeignKey(CategoryRoom, default='', related_name='room_category', on_delete=models.CASCADE,
                                 verbose_name='Название категории')
    volume = models.ForeignKey(VolumeRoom, default='', related_name='room_volume', on_delete=models.CASCADE,
                               verbose_name='Вместительность категории')
    images = models.ImageField(null=True, blank=True, verbose_name='Вместительность категории')

    class Meta:
        verbose_name = 'Комната'
        verbose_name_plural = 'Комнаты'

    def __str__(self):
        return self.name


class Booking(models.Model):
    # Book_Status_CHOICES = [
    #     ('ANF', 'Admin_Not_confirmed'),
    #     ('ACO', 'Admin_Confirmed'),
    #     ('ARE', 'Admin_Rejected'),
    #     ('ONF', 'Online_Not_confirmed'),
    #     ('OCO', 'Online_Confirmed'),
    #     ('ORE', 'Online_Rejected'),
    # ]
    #
    # BOOK_PAY_CHOICES = [
    #     ('Paid', 'Paid'),
    #     ('Unpaid', 'Unpaid'),
    # ]

    date_from = models.DateField(verbose_name='Бронировать с')
    date_to = models.DateField(verbose_name='Бронировать до')
    comment = models.CharField(max_length=170, blank=True, verbose_name='Комментарий')
    # Admin_Not_confirmed = 'ANF'
    # Admin_Confirmed = 'ACO'
    # Admin_Rejected = 'ARE'
    # Online_Not_confirmed = 'ONF'
    # Online_Confirmed = 'OCO'
    # Online_Rejected = 'ORE'

    book_status = models.ForeignKey(BookStatus, default=4, verbose_name='Статус брони', on_delete=models.CASCADE)
    book_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания брони')
    room = models.ForeignKey(Room, default='', on_delete=models.CASCADE, verbose_name='Комната')
    # Paid = 'PA'
    # Unpaid = 'UP'
    book_pay_status = models.ForeignKey(BookPayStatus, default=2, verbose_name='Статус оплаты',
                                        on_delete=models.CASCADE)
    has_child = models.BooleanField(default=False, blank=True, verbose_name='Есть ли ребенок')
    clientName = models.CharField(max_length=64, verbose_name='Имя клиента')
    clientSurname = models.CharField(max_length=64, verbose_name='Фамилия клиента')
    clientEmail = models.EmailField(verbose_name='Email клиента')
    clientPhone = models.IntegerField(verbose_name='Номер телефона клиента')
    totalsum = models.IntegerField(verbose_name='Полная стоимость', default=0)
    room_category_stats = models.CharField(verbose_name='Категория комнаты для статистики', max_length=64,
                                           blank=True, default='')
    date_mass = ArrayField(models.DateField(verbose_name='Даты', blank=True, null=True, default=None),
                           default=list, blank=True)

    class Meta:
        verbose_name = 'Бронь'
        verbose_name_plural = 'Брони'

    def __str__(self):
        name = self.clientName + ' ' + self.clientSurname
        email = self.clientEmail
        booking = name + ', ' + email
        return booking

    def save(self, *args, **kwargs):
        import datetime
        from .functions import get_date_array
        # self.date_from += datetime.date(self.date_from)
        # day_delta = datetime.timedelta(days=1)
        if not self.date_mass:
            a = get_date_array(self.date_from, self.date_to)
        # if not self.date_mass:
            self.date_mass += a

        # if self.totalsum == 0:
        if self.totalsum == 0:
            self.totalsum += self.room.price * (len(self.date_mass))
            # self.totalsum.save()
        if self.room_category_stats == '':
            self.room_category_stats += self.room.category.name
        super(Booking, self).save(*args, **kwargs)


class BookSummary(Booking):
    class Meta:
        proxy = True
        verbose_name = 'Статистика брони'
        verbose_name_plural = 'Статистка бронирования'

templates/change_list.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("book_status-chart");
            {% regroup cl.queryset|dictsort:"book_status" by get_book_status_display as book_status_list %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for book_status in book_status_list %}'{{ book_status.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for book_status in book_status_list %}'{{ book_status.list|length }}',{% endfor %}],
                        backgroundColor: [{% for book_status in book_status_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options: options
            });
            ctx = document.getElementById("book_pay_status-chart");
            {% regroup cl.queryset|dictsort:"book_pay_status" by book_pay_status as book_pay_status_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for book_pay_status in book_pay_status_list %}'{{ book_pay_status.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for book_pay_status in book_pay_status_list %}'{{ book_pay_status.list|length }}',{% endfor %}],
                        backgroundColor: [{% for book_pay_status in book_pay_status_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
            ctx = document.getElementById("room_category_stats-chart");
            {% regroup cl.queryset|dictsort:"room_category_stats" by get_room_category_stats_display as room_category_stats_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for room_category_stats in room_category_stats_list %}'{{ room_category_stats.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for room_category_stats in room_category_stats_list %}'{{ room_category_stats.list|length }}',{% endfor %}],
                        backgroundColor: [{% for room_category_stats in room_category_stats_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <h1> Graphs </h1>
    <hr>
    <div class="row">
        <div class="col-sm-4">
            <canvas id="book_status-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="book_pay_status-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="room_category_stats-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

templates/charts.html
{% extends "admin/change_list.html" %}
{% load static %}

{% block extrahead %}
{{ block.super }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', () => {
  const ctx = document.getElementById('myChart').getContext('2d');

  // Sample data
  const chartData = {{ chart_data | safe }};

  // Parse the dates to JS
  chartData.forEach((d) => {
    d.x = new Date(d.date);
  });

  const chart = new Chart(ctx, {
    type: 'bar',
    data: {
      datasets: [
        {
          label: 'New visitors',
          data: chartData,
          backgroundColor: 'rgba(220,20,20,0.5)',
        },
      ],
    },
    options: {
      responsive: true,
      scales: {
        xAxes: [
          {
            type: 'time',
            time: {
              unit: 'day',
              round: 'day',
              displayFormats: {
                day: 'MMM D',
              },
            },
          },
        ],
        yAxes: [
          {
            ticks: {
              beginAtZero: true,
            },
          },
        ],
      },
    },
  });

  // Reload chart data from the backend on button click
  const btn = document.querySelector('#reload');
  btn.addEventListener('click', async() => {
    const res = await fetch("/admin/web/emailsubscriber/chart_data/");
    const json = await res.json();
    json.forEach((d) => {
      d.x = new Date(d.date);
    });
    chart.data.datasets[0].data = json;
    chart.update();
  });
});
</script>
{% endblock %}

{% block content %}
<!-- Render our chart -->
<div style="width: 80%;">
  <canvas style="margin-bottom: 30px; width: 60%; height: 50%;" id="myChart"></canvas>
</div>

<button id="reload" style="margin: 1rem 0">Reload chart data</button>
<!-- Render the rest of the ChangeList view -->
{{ block.super }}
{% endblock %}

templates/charts3.html
{% extends "admin/change_list.html" %}
{% load staticfiles %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.min.js"></script>
    <script>
        var randomColorGenerator = function () {
            return '#' + (Math.random().toString(16) + '0000000').slice(2, 8);
        };
        var options = {
            responsive: true,
            maintainAspectRatio: true,
            legend: {
                position: 'left'
            },
            title: {
                display: true
            },
            animation: {
                animateScale: true,
                animateRotate: true
            }
        };
        window.onload = function () {
            var ctx = document.getElementById("room_category_stats-chart");
            {% regroup cl.queryset|dictsort:"room_category_stats" by get_room_category_stats_display as room_category_stats_list %}
            var lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for room_category_stats in room_category_stats_list %}'{{ room_category_stats.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for room_category_stats in room_category_stats_list %}'{{ room_category_stats.list|length }}',{% endfor %}],
                        backgroundColor: [{% for room_category_stats in room_category_stats_list %}randomColorGenerator(),{% endfor %}]
                    }]
                },
                options: options
            });
            var ctx = document.getElementById("book_status-chart");
            {% regroup cl.queryset|dictsort:"book_status" by grades as book_status_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for book_status in book_status_list %}'{{ book_status.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for book_status in book_status_list %}'{{ book_status.list|length }}',{% endfor %}],
                        backgroundColor: [{% for book_status in book_status_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
            var ctx = document.getElementById("book_pay_status-chart");
            {% regroup cl.queryset|dictsort:"book_pay_status" by get_book_pay_status_display as book_pay_status_list %}
            lineChart = new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: [{% for book_pay_status in book_pay_status_list %}'{{ book_pay_status.grouper }}',{% endfor %}],
                    datasets: [{
                        data: [{% for book_pay_status in book_pay_status_list %}'{{ book_pay_status.list|length }}',{% endfor %}],
                        backgroundColor: [{% for book_pay_status in book_pay_status_list %}randomColorGenerator(),{% endfor %}]
                    }]
                }, options: options
            });
        }
    </script>
{% endblock %}
{% block content %}
    <h1> Graphs </h1>
    <hr>
    <div class="row">
        <div class="col-sm-4">
            <canvas id="room_category_stats-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="book_status-chart" style="width: 100px !important;"></canvas>
        </div>
        <div class="col-sm-4">
            <canvas id="book_pay_status-chart" style="width: 100px !important;"></canvas>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

templates/sale_summary_change_list.html
{% extends "admin/change_list.html" %}
{% load static %}
{% load humanize %}
{{ my_num|intcomma }}
{% block content_title %}
    <h1> Bookings Summary </h1>
{% endblock %}

    <!-- Our content goes here... -->

{% block pagination %}{% endblock %}

{% block result_list %}
<div class="results">
    <table>
    <thead>
      <tr>
        <th>
          <div class="text">
            <a href="#">Pay Status</a>
          </div>
        </th>
        <th>
          <div class="text">
            <a href="#">Status</a>
          </div>
        </th>
        <th>
          <div class="text">
            <a href="#">Total</a>
          </div>
        </th>
        <th>
          <div class="text">
            <a href="#">Total Sales</a>
          </div>
        </th>
        <th>
          <div class="text">
            <a href="#">
              <strong>% Of Total Sales</strong>
            </a>
          </div>
        </th>
      </tr>
    </thead>

    <tbody>
      {% for row in summary %}
      <tr class="{% cycle 'row1' 'row2' %}">
        <td> {{ row.book_pay_status }} </td>
        <td> {{ row.book_status }} </td>

        <td> {{ row.total | intcomma }} </td>
        <td> {{ row.total_sales | default:0 | intcomma }}c </td>
        <td>
          <strong>
          {{ row.total_sales |
              default:0 |
              percentof:summary_total.totalsum }}
          </strong>
        </td>
      </tr>
      {% endfor %}
    </tbody>

  </table>
  <div class="results">
    <table>
        <!-- ... -->
        <tr style="font-weight:bold; border-top:2px solid #DDDDDD;">
            <td> Total </td>
            <td> {{ summary_total.total | intcomma }} </td>
            <td> {{ summary_total.total_sales | default:0 }}$ </td>
            <td> 100% </td>
        </tr>
    </table>
</div>
</div>
<div class="results">
    <!-- ... -->
    <h2> Sales over time </h2>
    <style>
    .bar-chart {
      display: flex;
      justify-content: space-around;
      height: 160px;
      padding-top: 60px;
      overflow: hidden;
    }
    .bar-chart .bar {
        flex: 100%;
        align-self: flex-end;
        margin-right: 2px;
        position: relative;
        background-color: #79aec8;
    }
    .bar-chart .bar:last-child {
        margin: 0;
    }
    .bar-chart .bar:hover {
        background-color: #417690;
    }
    .bar-chart .bar .bar-tooltip {
        position: relative;
        z-index: 999;
    }
    .bar-chart .bar .bar-tooltip {
        position: absolute;
        top: -60px;
        left: 50%;
        transform: translateX(-50%);
        text-align: center;
        font-weight: bold;
        opacity: 0;
    }
    .bar-chart .bar:hover .bar-tooltip {
        opacity: 1;
    }
    </style>
    <div class="results">
        <div class="bar-chart">
        {% for x in summary_over_time %}
            <div class="bar" style="height:{{x.pct}}%">
                <div class="bar-tooltip">
                    {{x.total | default:0 | intcomma }}<br>
                    {{x.period | date:"d/m/Y"}}
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
<!-- ... -->
{% endblock %}